Update the example to reflect current API (#131)
# What does this PR do?
Update the example to reflect current API

## Test Plan

Copy paste the example in the README and check the output. Without this
change an error is raised:

```python
python3 hello.py 
Traceback (most recent call last):
  File "/Users/bmuthuka/wa/meta-llama/baiju-experiments/hello.py", line 8, in <module>
    response = client.inference.chat_completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/myml/lib/python3.12/site-packages/llama_stack_client/_utils/_utils.py", line 274, in wrapper
    raise TypeError(msg)
TypeError: Missing required arguments; Expected either ('messages' and 'model_id') or ('messages', 'model_id' and 'stream') arguments to be given
```